"""Authentication and server-side authorization persistence.

PostgreSQL is used when configured through ``configure_database``. SQLite is
retained only for local development and tests.
"""

from __future__ import annotations

import hashlib
import hmac
import secrets
import sqlite3
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import pandas as pd


ROLES = {
    "Administrator": {"levels": {"National", "County", "Sub-county", "Ward"}, "admin": True},
    "President": {"levels": {"National", "County", "Sub-county", "Ward"}, "admin": False},
    "Governor": {"levels": {"County", "Sub-county", "Ward"}, "admin": False},
    "Senator": {"levels": {"County", "Sub-county", "Ward"}, "admin": False},
    "Women Representative": {"levels": {"County", "Sub-county", "Ward"}, "admin": False},
    "MP": {"levels": {"Sub-county", "Ward"}, "admin": False},
    "MCA": {"levels": {"Ward"}, "admin": False},
}
PASSWORD_ITERATIONS = 310_000
_DATABASE_URL: str | None = None


def configure_database(url: str | None) -> None:
    global _DATABASE_URL
    _DATABASE_URL = url.strip() if url and url.strip() else None


def using_postgres() -> bool:
    return bool(_DATABASE_URL)


def utc_now() -> str:
    return datetime.now(timezone.utc).isoformat()


def database_path(root: Path) -> Path:
    path = root / "data" / "auth.sqlite3"
    path.parent.mkdir(parents=True, exist_ok=True)
    return path


def connect(root: Path):
    if using_postgres():
        try:
            import psycopg
            from psycopg.rows import dict_row
        except ImportError as error:
            raise RuntimeError("PostgreSQL authentication requires psycopg[binary].") from error
        return psycopg.connect(_DATABASE_URL, row_factory=dict_row)
    connection = sqlite3.connect(database_path(root))
    connection.row_factory = sqlite3.Row
    return connection


def _execute(connection, query: str, parameters: tuple = ()):
    return connection.execute(query.replace("?", "%s") if using_postgres() else query, parameters)


def initialize(root: Path) -> None:
    if using_postgres():
        statements = [
            """CREATE TABLE IF NOT EXISTS users (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                username TEXT NOT NULL UNIQUE,
                auth_subject TEXT,
                display_name TEXT NOT NULL,
                role TEXT NOT NULL CHECK (role IN ('Administrator', 'President', 'Governor', 'Senator', 'Women Representative', 'MP', 'MCA')),
                password_hash TEXT NOT NULL,
                active BOOLEAN NOT NULL DEFAULT TRUE,
                created_at TEXT NOT NULL,
                last_login_at TEXT
            )""",
            """CREATE TABLE IF NOT EXISTS user_scopes (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                dataset TEXT, county TEXT, sub_county TEXT, constituency TEXT, ward TEXT
            )""",
            """CREATE TABLE IF NOT EXISTS audit_log (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                actor_username TEXT NOT NULL, action TEXT NOT NULL, target_username TEXT, detail TEXT, created_at TEXT NOT NULL
            )""",
            "CREATE INDEX IF NOT EXISTS idx_user_scopes_user_id ON user_scopes(user_id)",
        ]
        with connect(root) as connection:
            for statement in statements:
                _execute(connection, statement)
        return
    with connect(root) as connection:
        connection.executescript(
            """CREATE TABLE IF NOT EXISTS users (
                id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT NOT NULL UNIQUE, auth_subject TEXT,
                display_name TEXT NOT NULL, role TEXT NOT NULL, password_hash TEXT NOT NULL,
                active INTEGER NOT NULL DEFAULT 1, created_at TEXT NOT NULL, last_login_at TEXT,
                CHECK (role IN ('Administrator', 'President', 'Governor', 'Senator', 'Women Representative', 'MP', 'MCA'))
            );
            CREATE TABLE IF NOT EXISTS user_scopes (
                id INTEGER PRIMARY KEY AUTOINCREMENT, user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                dataset TEXT, county TEXT, sub_county TEXT, constituency TEXT, ward TEXT
            );
            CREATE TABLE IF NOT EXISTS audit_log (
                id INTEGER PRIMARY KEY AUTOINCREMENT, actor_username TEXT NOT NULL, action TEXT NOT NULL,
                target_username TEXT, detail TEXT, created_at TEXT NOT NULL
            );"""
        )
        columns = {row["name"] for row in _execute(connection, "PRAGMA table_info(users)").fetchall()}
        if "auth_subject" not in columns:
            _execute(connection, "ALTER TABLE users ADD COLUMN auth_subject TEXT")


def _password_hash(password: str, salt: bytes | None = None) -> str:
    salt = salt or secrets.token_bytes(16)
    digest = hashlib.pbkdf2_hmac("sha256", password.encode("utf-8"), salt, PASSWORD_ITERATIONS)
    return f"pbkdf2_sha256${PASSWORD_ITERATIONS}${salt.hex()}${digest.hex()}"


def _password_matches(password: str, stored: str) -> bool:
    try:
        scheme, iterations, salt_hex, digest_hex = stored.split("$", 3)
        if scheme != "pbkdf2_sha256":
            return False
        calculated = hashlib.pbkdf2_hmac("sha256", password.encode("utf-8"), bytes.fromhex(salt_hex), int(iterations))
        return hmac.compare_digest(calculated.hex(), digest_hex)
    except (ValueError, TypeError):
        return False


def user_count(root: Path) -> int:
    initialize(root)
    with connect(root) as connection:
        return int(_execute(connection, "SELECT COUNT(*) AS count FROM users").fetchone()["count"])


def create_user(root: Path, username: str, display_name: str, role: str, password: str = "", scopes: list[dict[str, str | None]] | None = None, actor: str = "system", auth_subject: str | None = None) -> None:
    username = username.strip().lower()
    if not username or not display_name.strip() or role not in ROLES:
        raise ValueError("Username, display name, and a valid role are required.")
    if password and len(password) < 12:
        raise ValueError("A local password must contain at least 12 characters.")
    initialize(root)
    with connect(root) as connection:
        values = (username, auth_subject or username, display_name.strip(), role, _password_hash(password) if password else "oidc_only", utc_now())
        query = "INSERT INTO users (username, auth_subject, display_name, role, password_hash, created_at) VALUES (?, ?, ?, ?, ?, ?)"
        if using_postgres():
            user_id = _execute(connection, query + " RETURNING id", values).fetchone()["id"]
        else:
            user_id = _execute(connection, query, values).lastrowid
        for scope in scopes or []:
            _execute(connection, "INSERT INTO user_scopes (user_id, dataset, county, sub_county, constituency, ward) VALUES (?, ?, ?, ?, ?, ?)", (user_id, scope.get("dataset"), scope.get("county"), scope.get("sub_county"), scope.get("constituency"), scope.get("ward")))
        _execute(connection, "INSERT INTO audit_log (actor_username, action, target_username, detail, created_at) VALUES (?, ?, ?, ?, ?)", (actor, "create_user", username, role, utc_now()))


def authenticate(root: Path, username: str, password: str) -> dict[str, Any] | None:
    initialize(root)
    with connect(root) as connection:
        row = _execute(connection, "SELECT * FROM users WHERE username = ? AND active = 1", (username.strip().lower(),)).fetchone()
        if row is None or not _password_matches(password, row["password_hash"]):
            return None
        _execute(connection, "UPDATE users SET last_login_at = ? WHERE id = ?", (utc_now(), row["id"]))
        _execute(connection, "INSERT INTO audit_log (actor_username, action, target_username, detail, created_at) VALUES (?, ?, ?, ?, ?)", (row["username"], "login", row["username"], "", utc_now()))
        return dict(row)


def authenticate_oidc(root: Path, subject: str, email: str | None = None) -> dict[str, Any] | None:
    initialize(root)
    identities = [value.strip().lower() for value in [subject, email] if value]
    if not identities:
        return None
    placeholders = ",".join("?" for _ in identities)
    with connect(root) as connection:
        row = _execute(connection, f"SELECT * FROM users WHERE active = 1 AND (lower(auth_subject) IN ({placeholders}) OR lower(username) IN ({placeholders}))", tuple(identities + identities)).fetchone()
        if row is None:
            return None
        _execute(connection, "UPDATE users SET last_login_at = ? WHERE id = ?", (utc_now(), row["id"]))
        _execute(connection, "INSERT INTO audit_log (actor_username, action, target_username, detail, created_at) VALUES (?, ?, ?, ?, ?)", (row["username"], "oidc_login", row["username"], subject, utc_now()))
        return dict(row)


def scopes_for(root: Path, user_id: int) -> list[dict[str, str | None]]:
    initialize(root)
    with connect(root) as connection:
        rows = _execute(connection, "SELECT dataset, county, sub_county, constituency, ward FROM user_scopes WHERE user_id = ?", (user_id,)).fetchall()
        return [dict(row) for row in rows]


def list_users(root: Path) -> pd.DataFrame:
    initialize(root)
    with connect(root) as connection:
        rows = _execute(connection, "SELECT id, username, auth_subject, display_name, role, active, created_at, last_login_at FROM users ORDER BY username").fetchall()
    return pd.DataFrame([dict(row) for row in rows])


def update_user(root: Path, user_id: int, role: str, active: bool, scopes: list[dict[str, str | None]], actor: str) -> None:
    if role not in ROLES:
        raise ValueError("Invalid role.")
    initialize(root)
    with connect(root) as connection:
        row = _execute(connection, "SELECT username FROM users WHERE id = ?", (user_id,)).fetchone()
        if row is None:
            raise ValueError("User not found.")
        _execute(connection, "UPDATE users SET role = ?, active = ? WHERE id = ?", (role, int(active), user_id))
        _execute(connection, "DELETE FROM user_scopes WHERE user_id = ?", (user_id,))
        for scope in scopes:
            _execute(connection, "INSERT INTO user_scopes (user_id, dataset, county, sub_county, constituency, ward) VALUES (?, ?, ?, ?, ?, ?)", (user_id, scope.get("dataset"), scope.get("county"), scope.get("sub_county"), scope.get("constituency"), scope.get("ward")))
        _execute(connection, "INSERT INTO audit_log (actor_username, action, target_username, detail, created_at) VALUES (?, ?, ?, ?, ?)", (actor, "update_user", row["username"], f"role={role}; active={active}", utc_now()))


def is_admin(user: dict[str, Any]) -> bool:
    return bool(ROLES.get(user.get("role"), {}).get("admin"))


def allowed_levels(user: dict[str, Any]) -> set[str]:
    return set(ROLES.get(user.get("role"), {}).get("levels", set()))


def _matches_scope(row: pd.Series, scope: dict[str, str | None], dataset: str) -> bool:
    if scope.get("dataset") and scope["dataset"] != dataset:
        return False
    for column in ("county", "sub_county", "constituency", "ward"):
        value = scope.get(column)
        if value and (column not in row.index or str(row.get(column, "")) != value):
            return False
    return any(scope.get(column) for column in ("county", "sub_county", "constituency", "ward"))


def filter_frame(frame: pd.DataFrame, user: dict[str, Any], dataset: str, root: Path) -> pd.DataFrame:
    if is_admin(user) or user.get("role") == "President":
        return frame.copy()
    scopes = scopes_for(root, int(user["id"]))
    if not scopes:
        return frame.iloc[0:0].copy()
    mask = frame.apply(lambda row: any(_matches_scope(row, scope, dataset) for scope in scopes), axis=1)
    return frame.loc[mask].copy()


def filter_bundle(bundle: dict[str, Any], user: dict[str, Any], dataset: str, root: Path) -> dict[str, Any]:
    return {**bundle, **{name: filter_frame(bundle[name], user, dataset, root) for name in ("history", "snapshot", "master", "summary")}}


def migrate_sqlite_to_postgres(root: Path, target_url: str) -> int:
    """Copy local users and scopes into PostgreSQL; safe to rerun by username."""
    source = sqlite3.connect(database_path(root))
    source.row_factory = sqlite3.Row
    configure_database(target_url)
    initialize(root)
    with source, connect(root) as destination:
        users = source.execute("SELECT username, auth_subject, display_name, role, password_hash, active, created_at, last_login_at FROM users ORDER BY id").fetchall()
        migrated = 0
        for user in users:
            if using_postgres():
                row = _execute(destination, "INSERT INTO users (username, auth_subject, display_name, role, password_hash, active, created_at, last_login_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?) ON CONFLICT (username) DO UPDATE SET auth_subject = EXCLUDED.auth_subject, display_name = EXCLUDED.display_name, role = EXCLUDED.role, password_hash = EXCLUDED.password_hash, active = EXCLUDED.active, last_login_at = EXCLUDED.last_login_at RETURNING id", tuple(user)).fetchone()
            else:
                row = _execute(destination, "SELECT id FROM users WHERE username = ?", (user["username"],)).fetchone()
            user_id = row["id"]
            _execute(destination, "DELETE FROM user_scopes WHERE user_id = ?", (user_id,))
            source_scopes = source.execute("SELECT dataset, county, sub_county, constituency, ward FROM user_scopes WHERE user_id = (SELECT id FROM users WHERE username = ?)", (user["username"],)).fetchall()
            for scope in source_scopes:
                _execute(destination, "INSERT INTO user_scopes (user_id, dataset, county, sub_county, constituency, ward) VALUES (?, ?, ?, ?, ?, ?)", (user_id, scope["dataset"], scope["county"], scope["sub_county"], scope["constituency"], scope["ward"]))
            migrated += 1
    return migrated
